services:
    Google_Client:
        class: Google_Client
        calls:
            - [setDeveloperKey, ['%env(GOOGLE_API_KEY)%']]
            - [setClientId, ['109596151554951074503']]
            - [setClientSecret, ['-b4dvYtNa9hTya31pU2cFCQV']]
